name: Build Battle Mania APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Check project
        working-directory: app/app-sourcecode
        run: |
          echo "Project directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Gradle version:"
          chmod +x gradlew
          ./gradlew --version

      - name: Build APK
        working-directory: app/app-sourcecode
        run: |
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Find APK
        if: success()
        run: |
          find app/app-sourcecode -name "*.apk" -type f -print

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Battle-Mania-APK
          path: app/app-sourcecode/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
